# Generated by Django 5.0.1 on 2024-02-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'feedmail',
            },
        ),
        migrations.DeleteModel(
            name='feed',
        ),
    ]
