# Generated by Django 5.0.1 on 2024-02-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_feedmail_delete_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teja',
            name='phonenumber',
            field=models.IntegerField(max_length=15),
        ),
    ]
